# Generated by Django 5.2.13 on 2026-04-12 05:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("coin_reward", models.PositiveIntegerField(default=0)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("one_time", "One-Time"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "week_schedule",
                    models.CharField(
                        choices=[
                            ("every_week", "Every Week"),
                            ("alternating", "Alternating Weeks"),
                        ],
                        default="every_week",
                        help_text="Controls whether this chore is active every week or alternating weeks (shared custody).",
                        max_length=12,
                    ),
                ),
                (
                    "schedule_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Reference date for alternating weeks. Any date during an 'on' week. Uses ISO week parity to determine active weeks.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = available to all children.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ChoreCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_date",
                    models.DateField(
                        help_text="The calendar date (or period-start for weekly) this completion covers."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional note from child."),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reward_amount_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Reward amount frozen at submission time.",
                        max_digits=8,
                    ),
                ),
                (
                    "coin_reward_snapshot",
                    models.PositiveIntegerField(
                        help_text="Coin reward frozen at submission time."
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="chores.chore",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_chore_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chore_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "rejected"), _negated=True),
                        fields=("chore", "user", "completed_date"),
                        name="unique_active_chore_completion_per_day",
                    )
                ],
            },
        ),
    ]
