# Generated by Django 5.2.12 on 2026-04-06 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("timecard_ready", "Timecard Ready"),
                            ("timecard_approved", "Timecard Approved"),
                            ("badge_earned", "Badge Earned"),
                            ("project_approved", "Project Approved"),
                            ("project_changes", "Changes Requested"),
                            ("payout_recorded", "Payout Recorded"),
                            ("skill_unlocked", "Skill Unlocked"),
                            ("milestone_completed", "Milestone Completed"),
                        ],
                        max_length=25,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
