# Generated by Django 5.2.13 on 2026-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_step_milestone_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("timecard_ready", "Timecard Ready"),
                    ("timecard_approved", "Timecard Approved"),
                    ("badge_earned", "Badge Earned"),
                    ("project_approved", "Project Approved"),
                    ("project_changes", "Changes Requested"),
                    ("payout_recorded", "Payout Recorded"),
                    ("skill_unlocked", "Skill Unlocked"),
                    ("milestone_completed", "Milestone Completed"),
                    ("redemption_requested", "Redemption Requested"),
                    ("chore_submitted", "Chore Submitted"),
                    ("chore_approved", "Chore Approved"),
                    ("exchange_requested", "Exchange Requested"),
                    ("exchange_approved", "Exchange Approved"),
                    ("exchange_denied", "Exchange Denied"),
                ],
                max_length=25,
            ),
        ),
    ]
