# Generated by Django 5.1.15 on 2026-04-18 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("award", "Award"),
                            ("ledger", "Ledger"),
                            ("rpg", "RPG"),
                            ("quest", "Quest"),
                            ("habit", "Habit"),
                            ("timecard", "Timecard"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=48)),
                ("summary", models.CharField(max_length=200)),
                ("coins_delta", models.IntegerField(blank=True, null=True)),
                (
                    "money_delta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("xp_delta", models.IntegerField(blank=True, null=True)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["subject", "-occurred_at"],
                        name="activity_ac_subject_2adcf3_idx",
                    ),
                    models.Index(
                        fields=["category", "-occurred_at"],
                        name="activity_ac_categor_a1be6c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"],
                        name="activity_ac_event_t_e92755_idx",
                    ),
                ],
            },
        ),
    ]
