# Generated by Django 5.1.15 on 2026-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_entry_year',
            field=models.PositiveIntegerField(blank=True, help_text='Calendar year of August she entered 9th grade (e.g. 2025).', null=True),
        ),
    ]
