# Generated by Django 5.2.12 on 2026-04-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("projects_completed", "Projects Completed"),
                            ("hours_worked", "Hours Worked"),
                            ("category_projects", "Category Projects"),
                            ("streak_days", "Streak Days"),
                            ("first_project", "First Project"),
                            ("first_clock_in", "First Clock In"),
                            ("materials_under_budget", "Materials Under Budget"),
                            ("perfect_timecard", "Perfect Timecard"),
                            ("skill_level_reached", "Skill Level Reached"),
                            ("skills_unlocked", "Skills Unlocked"),
                            ("skill_categories_breadth", "Skill Categories Breadth"),
                            ("hours_in_day", "Hours in a Day"),
                            ("photos_uploaded", "Photos Uploaded"),
                            ("total_earned", "Total Earned"),
                            ("days_worked", "Days Worked"),
                            ("cross_category_unlock", "Cross-Category Unlock"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criteria_value", models.JSONField(default=dict)),
                ("xp_bonus", models.PositiveIntegerField(default=0)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("level_names", models.JSONField(default=dict)),
                ("is_locked_by_default", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="projects.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProjectSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_weight", models.IntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="projects.project",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "skill")},
            },
        ),
        migrations.CreateModel(
            name="MilestoneSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_amount", models.IntegerField(default=15)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="projects.projectmilestone",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("milestone", "skill")},
            },
        ),
        migrations.CreateModel(
            name="SkillPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_level", models.IntegerField(default=2)),
                (
                    "required_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="achievements.skill",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="achievements.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("skill", "required_skill")},
            },
        ),
        migrations.CreateModel(
            name="SkillProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=0)),
                ("unlocked", models.BooleanField(default=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="achievements.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "badge")},
            },
        ),
    ]
