# Generated by Django 5.1.15 on 2026-04-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("achievements", "0013_alter_badge_criteria_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji shown on the picker.",
                        max_length=10,
                    ),
                ),
                (
                    "default_intensity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Pre-selected intensity in the log modal.",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MovementDailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_on", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_daily_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_on"],
                        name="movement_mo_user_id_5be7a5_idx",
                    )
                ],
                "unique_together": {("user", "occurred_on")},
            },
        ),
        migrations.CreateModel(
            name="MovementSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Capped to MovementSessionService.MAX_DURATION_MINUTES at log time."
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(
                        help_text="Local-day bucket used by the anti-farm gate."
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "xp_awarded",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="XP pool actually distributed (0 if over the daily reward cap).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="movement.movementtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_on"],
                        name="movement_mo_user_id_737d83_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovementTypeSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xp_weight",
                    models.IntegerField(
                        default=1,
                        help_text="Relative share of the session's XP pool this skill receives.",
                    ),
                ),
                (
                    "movement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="movement.movementtype",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("movement_type", "skill")},
            },
        ),
    ]
