# Generated by Django 5.1.15 on 2026-08-27 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grams_per_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Filament allowance per calendar month, in grams. Null = unlimited.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "minutes_per_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Print-time allowance per calendar month, in minutes. Null = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="When false the caps are ignored entirely (still ledgered, never enforced).",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_budget",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="PrinterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'X1C in the garage'.",
                        max_length=80,
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        help_text="Printer serial number. Forms the MQTT topic: device/<serial>/report.",
                        max_length=32,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="X1C",
                        help_text="Informational only — X1C / X1E / P1S / A1. Does not change protocol handling.",
                        max_length=40,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("local", "Local MQTT (LAN)"),
                            ("cloud", "Bambu Cloud MQTT"),
                        ],
                        default="local",
                        help_text="Which MQTT transport the listener opens. Swapping local↔cloud is a config change; both speak the same report schema.",
                        max_length=8,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="LAN IP or hostname. Local transport only — cloud derives its host from settings.",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=8883,
                        help_text="MQTT TLS port. 8883 for both local and Bambu Cloud.",
                    ),
                ),
                (
                    "encrypted_secret",
                    models.BinaryField(
                        blank=True,
                        default=b"",
                        help_text="Fernet-encrypted JSON: {access_code, cloud_user_id, cloud_token}. Written via PrinterProfile.set_secrets(); never serialized out.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive printers are skipped by the listener supervisor.",
                    ),
                ),
                ("last_report_at", models.DateTimeField(blank=True, null=True)),
                ("last_gcode_state", models.CharField(blank=True, max_length=24)),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        help_text="Last connection/transport error, surfaced in the parent UI.",
                        max_length=300,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printers",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subtask_name",
                    models.CharField(
                        help_text="Raw print.subtask_name as reported. Never normalised in place.",
                        max_length=200,
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True,
                        help_text="subtask_name run through matching.normalize_subtask_name(). What we match on.",
                        max_length=200,
                    ),
                ),
                ("gcode_file", models.CharField(blank=True, max_length=255)),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=40)),
                ("subtask_id", models.CharField(blank=True, max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=12,
                    ),
                ),
                (
                    "gcode_state_raw",
                    models.CharField(
                        blank=True,
                        help_text="The literal print.gcode_state string, kept for diagnosis when firmware adds values.",
                        max_length=24,
                    ),
                ),
                ("layer_num", models.PositiveIntegerField(default=0)),
                ("total_layer_num", models.PositiveIntegerField(default=0)),
                ("percent_complete", models.PositiveSmallIntegerField(default=0)),
                ("remaining_minutes", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_report_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link_source",
                    models.CharField(
                        choices=[
                            ("auto", "Matched automatically"),
                            ("manual", "Linked by a parent"),
                            ("unlinked", "Not linked"),
                        ],
                        default="unlinked",
                        max_length=10,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        help_text="Canonical HMS code, e.g. '0300_0100_0002_0001', or 'print_error:<n>'.",
                        max_length=40,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable decode. This is what the timeline shows instead of a number.",
                        max_length=300,
                    ),
                ),
                ("failure_severity", models.CharField(blank=True, max_length=16)),
                (
                    "grams_debited",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("minutes_debited", models.IntegerField(blank=True, null=True)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="printing.printerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denormalised from request.user at link time; null while unmatched.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintJobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("progress", "Progress"),
                            ("paused", "Paused"),
                            ("resumed", "Resumed"),
                            ("hms", "Printer alert"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("linked", "Linked to request"),
                            ("unlinked", "Unlinked from request"),
                            ("budget", "Budget debited"),
                            ("note", "Note"),
                        ],
                        max_length=12,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Canonical HMS code when kind=hms/failed; empty otherwise.",
                        max_length=40,
                    ),
                ),
                ("severity", models.CharField(blank=True, max_length=16)),
                ("layer_num", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "percent_complete",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form extras (raw hms attr/code pair, remaining minutes, debit math).",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="printing.printjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrintRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Scraped from the link's OpenGraph title, or typed for uploads.",
                        max_length=160,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("makerworld", "MakerWorld"),
                            ("printables", "Printables"),
                            ("thingiverse", "Thingiverse"),
                            ("other_url", "Other link"),
                            ("upload", "Uploaded model"),
                        ],
                        default="other_url",
                        max_length=16,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("source_author", models.CharField(blank=True, max_length=120)),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Remote og:image URL. Kept even after we cache a local copy, as provenance.",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Locally cached copy of thumbnail_url, fetched by apps.printing.tasks.cache_request_thumbnail. Preferred by the serializer so cards keep working when the model host rotates URLs.",
                        null=True,
                        upload_to="print-requests/thumbs/",
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded STL/3MF/step. Only set for SourceKind.UPLOAD.",
                        null=True,
                        upload_to="print-requests/models/",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Free text — 'glow in the dark green'.", max_length=40
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why she wants it. Required — this is the point of the flow."
                    ),
                ),
                ("needed_by", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("printing", "Printing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("parent_notes", models.TextField(blank=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Minted once at approval, e.g. 'req-0042-dragon'. Empty until then. Unique among non-empty values — see the partial constraint in Meta.",
                        max_length=80,
                    ),
                ),
                (
                    "plate_filename",
                    models.CharField(
                        blank=True,
                        help_text="What the parent must name the sliced plate, e.g. 'req-0042-dragon.3mf'.",
                        max_length=120,
                    ),
                ),
                (
                    "estimated_grams",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Filament estimate from Bambu Studio, in grams. The MQTT report does NOT carry consumed filament, so this is what the budget debits.",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Print-time estimate from the slicer, in minutes. Informational at approval.",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "print_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of jobs that have bound to this request (re-prints included).",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="printjob",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="printing.printrequest",
            ),
        ),
        migrations.CreateModel(
            name="PrintBudgetLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period_month",
                    models.DateField(
                        db_index=True,
                        help_text="First day of the local (America/Phoenix) month this entry counts against. Denormalised so the monthly rollup is an indexed equality filter rather than a timezone-sensitive range scan over created_at.",
                    ),
                ),
                (
                    "grams",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("minutes", models.IntegerField(default=0)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("print_completed", "Print completed"),
                            ("print_failed", "Print failed (partial)"),
                            ("adjustment", "Manual adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent who made a manual adjustment; null for automatic debits.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_budget_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_entries",
                        to="printing.printjob",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_entries",
                        to="printing.printrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="printerprofile",
            index=models.Index(fields=["serial"], name="printing_pr_serial_cc1b7d_idx"),
        ),
        migrations.AddConstraint(
            model_name="printerprofile",
            constraint=models.UniqueConstraint(
                fields=("family", "serial"), name="uniq_printer_serial_per_family"
            ),
        ),
        migrations.AddIndex(
            model_name="printjobevent",
            index=models.Index(
                fields=["job", "created_at"], name="printing_pr_job_id_013ff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printrequest",
            index=models.Index(
                fields=["user", "status"], name="printing_pr_user_id_9a3ab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printrequest",
            index=models.Index(
                fields=["status", "needed_by"], name="printing_pr_status_79a61f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="printrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("slug",),
                name="uniq_print_request_slug_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="printjob",
            index=models.Index(
                fields=["request", "-started_at"], name="printing_pr_request_85dd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printjob",
            index=models.Index(
                fields=["user", "-started_at"], name="printing_pr_user_id_759cdc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="printjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("finished_at__isnull", True)),
                fields=("printer",),
                name="uniq_open_job_per_printer",
            ),
        ),
        migrations.AddIndex(
            model_name="printbudgetledger",
            index=models.Index(
                fields=["user", "period_month"], name="printing_pr_user_id_098430_idx"
            ),
        ),
    ]
