# Generated by Django 5.1.15 on 2026-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="gcode_start_time",
            field=models.CharField(
                blank=True,
                help_text="print.gcode_start_time as reported — unix seconds, as a string. The printer's own identity for this print RUN, and the only field that survives a listener restart, so it is what lets a restarted listener re-attach to this row instead of opening a second one for a print already in progress.",
                max_length=32,
            ),
        ),
    ]
