# Generated by Django 5.1.15 on 2026-08-29 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0002_printjob_gcode_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when a parent clears an unmatched print out of the Forge's 'Prints without a request' panel. A soft hide, not a delete: the job and its timeline stay for diagnosis, and clearing this field puts it back in the panel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="dismissed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
