# Generated by Django 5.1.15 on 2026-04-22 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('birthday', 'Birthday'), ('chapter_start', 'Chapter start'), ('chapter_end', 'Chapter end'), ('first_ever', 'First ever'), ('milestone', 'Milestone'), ('recap', 'Recap'), ('manual', 'Manual')], max_length=32)),
                ('occurred_on', models.DateField()),
                ('chapter_year', models.PositiveIntegerField(help_text='August-starting year the chapter covers (e.g. 2025 = Aug 2025–Jul 2026).')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('icon_slug', models.CharField(blank=True, max_length=80)),
                ('event_slug', models.CharField(blank=True, max_length=80)),
                ('related_object_type', models.CharField(blank=True, max_length=40)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronicle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['user', 'chapter_year'], name='chronicle_c_user_id_e660f8_idx'), models.Index(fields=['user', 'event_slug'], name='chronicle_c_user_id_74f907_idx'), models.Index(fields=['user', 'viewed_at'], name='chronicle_c_user_id_e50645_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'first_ever')), fields=('user', 'event_slug'), name='unique_first_ever_per_user')],
            },
        ),
    ]
