# Generated by Django 5.2.4 on 2026-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicleentry',
            name='is_private',
            field=models.BooleanField(default=False, help_text='True for child-authored journal entries — a privacy marker surfaces in the Yearbook UI. Does not gate read access: parents can still see the entry (the lock chip just makes privacy visible).'),
        ),
        migrations.AlterField(
            model_name='chronicleentry',
            name='kind',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('chapter_start', 'Chapter start'), ('chapter_end', 'Chapter end'), ('first_ever', 'First ever'), ('milestone', 'Milestone'), ('recap', 'Recap'), ('manual', 'Manual'), ('journal', 'Journal')], max_length=32),
        ),
    ]
