# Generated by Django 5.2.4 on 2026-04-22 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_chronicleentry_is_private_alter_chronicleentry_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chronicleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'journal')), fields=('user', 'occurred_on'), name='unique_journal_per_user_per_day'),
        ),
    ]
