# Generated by Django 5.2.4 on 2026-04-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_chronicleentry_unique_journal_per_user_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicleentry',
            name='kind',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('chapter_start', 'Chapter start'), ('chapter_end', 'Chapter end'), ('first_ever', 'First ever'), ('milestone', 'Milestone'), ('recap', 'Recap'), ('manual', 'Manual'), ('journal', 'Journal'), ('creation', 'Creation')], max_length=32),
        ),
    ]
