# Generated by Django 5.2.4 on 2026-04-14 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_habit_habitlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('egg', 'Pet Egg'), ('potion', 'Hatching Potion'), ('food', 'Pet Food'), ('cosmetic_frame', 'Avatar Frame'), ('cosmetic_title', 'Title'), ('cosmetic_theme', 'Dashboard Theme'), ('cosmetic_pet_accessory', 'Pet Accessory'), ('quest_scroll', 'Quest Scroll'), ('coin_pouch', 'Coin Pouch')], max_length=30)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('coin_value', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['item_type', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DropTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('clock_out', 'Clock Out'), ('chore_complete', 'Chore Complete'), ('homework_complete', 'Homework Complete'), ('milestone_complete', 'Milestone Complete'), ('badge_earned', 'Badge Earned'), ('quest_complete', 'Quest Complete'), ('perfect_day', 'Perfect Day'), ('habit_log', 'Habit Log')], max_length=30)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('min_level', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_table_entries', to='rpg.itemdefinition')),
            ],
            options={
                'ordering': ['trigger_type', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='DropLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('was_salvaged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_logs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_log_entries', to='rpg.itemdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='rpg.itemdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item__item_type', 'item__name'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
