# Generated by Django 5.2.4 on 2026-04-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_itemdefinition_droptable_droplog_userinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='active_frame',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'cosmetic_frame'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_frame', to='rpg.itemdefinition'),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='active_pet_accessory',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'cosmetic_pet_accessory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_pet_accessory', to='rpg.itemdefinition'),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='active_theme',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'cosmetic_theme'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_theme', to='rpg.itemdefinition'),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='active_title',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'cosmetic_title'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_title', to='rpg.itemdefinition'),
        ),
    ]
