# Generated by Django 5.2.4 on 2026-04-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_content_slugs_and_refs'),
        ('rpg', '0004_characterprofile_active_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='food_species',
            field=models.ForeignKey(blank=True, help_text='For food: the species that prefers this food (matches food_preference).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='pets.petspecies'),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='pet_species',
            field=models.ForeignKey(blank=True, help_text='For eggs: the species that hatches from this egg.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eggs', to='pets.petspecies'),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='potion_type',
            field=models.ForeignKey(blank=True, help_text='For potions: the variant this item represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_variants', to='pets.potiontype'),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
