# Generated by Django 5.1.15 on 2026-04-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_add_homework_created_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droptable',
            name='trigger_type',
            field=models.CharField(choices=[('clock_out', 'Clock Out'), ('chore_complete', 'Chore Complete'), ('homework_complete', 'Homework Complete'), ('homework_created', 'Homework Created'), ('milestone_complete', 'Milestone Complete'), ('project_complete', 'Project Complete'), ('badge_earned', 'Badge Earned'), ('quest_complete', 'Quest Complete'), ('perfect_day', 'Perfect Day'), ('habit_log', 'Habit Log')], max_length=30),
        ),
    ]
