# Generated by Django 5.1.15 on 2026-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_pr1_reward_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='streak_freeze_expires_at',
            field=models.DateField(blank=True, help_text="While set to today or later, a missed day doesn't reset the login streak. Consumed on use by the streak-freeze consumable.", null=True),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='item_type',
            field=models.CharField(choices=[('egg', 'Pet Egg'), ('potion', 'Hatching Potion'), ('food', 'Pet Food'), ('cosmetic_frame', 'Avatar Frame'), ('cosmetic_title', 'Title'), ('cosmetic_theme', 'Dashboard Theme'), ('cosmetic_pet_accessory', 'Pet Accessory'), ('quest_scroll', 'Quest Scroll'), ('coin_pouch', 'Coin Pouch'), ('consumable', 'Consumable')], max_length=30),
        ),
    ]
