# Generated by Django 5.1.15 on 2026-04-20 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0011_pr2_consumable_and_streak_freeze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*$', 'Slug must be lowercase a-z0-9 and hyphens.')])),
                ('image', models.ImageField(blank=True, upload_to='rpg-sprites/')),
                ('pack', models.CharField(db_index=True, default='user-authored', max_length=40)),
                ('frame_count', models.PositiveSmallIntegerField(default=1)),
                ('fps', models.PositiveSmallIntegerField(default=0)),
                ('frame_width_px', models.PositiveSmallIntegerField()),
                ('frame_height_px', models.PositiveSmallIntegerField()),
                ('frame_layout', models.CharField(choices=[('horizontal', 'Horizontal strip'), ('vertical', 'Vertical strip')], default='horizontal', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprites_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['pack', 'slug'], name='rpg_spritea_pack_a22397_idx')],
            },
        ),
    ]
