# Generated by Django 5.1.15 on 2026-04-20 17:39

import apps.rpg.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0012_sprite_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spriteasset',
            name='image',
            field=models.ImageField(blank=True, storage=apps.rpg.storage.sprite_storage, upload_to='rpg-sprites/'),
        ),
    ]
