# Generated by Django 5.1.15 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0015_character_boosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='unlocks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
