# Generated by Django 5.1.15 on 2026-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0016_characterprofile_unlocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='consumable_effects_used',
            field=models.JSONField(blank=True, default=list, help_text='Distinct consumable effect slugs ever used (for Alchemist-style badges).'),
        ),
    ]
