# Generated by Django 5.2.4 on 2026-04-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0018_characterprofile_active_trophy_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droptable',
            name='trigger_type',
            field=models.CharField(choices=[('clock_out', 'Clock Out'), ('chore_complete', 'Chore Complete'), ('homework_complete', 'Homework Complete'), ('homework_created', 'Homework Created'), ('milestone_complete', 'Milestone Complete'), ('project_complete', 'Project Complete'), ('badge_earned', 'Badge Earned'), ('quest_complete', 'Quest Complete'), ('perfect_day', 'Perfect Day'), ('habit_log', 'Habit Log'), ('daily_check_in', 'Daily Check-In'), ('savings_goal_complete', 'Savings Goal Complete'), ('journal_entry', 'Journal Entry'), ('creation_logged', 'Creation Logged')], max_length=30),
        ),
    ]
