# Generated by Django 5.2.13 on 2026-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentledger_bounty_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentledger",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("project_bonus", "Project Bonus"),
                    ("bounty_payout", "Bounty Payout"),
                    ("milestone_bonus", "Milestone Bonus"),
                    ("materials_reimbursement", "Materials Reimbursement"),
                    ("payout", "Payout"),
                    ("adjustment", "Adjustment"),
                    ("coin_exchange", "Coin Exchange"),
                ],
                max_length=25,
            ),
        ),
    ]
