# Generated by Django 5.2.4 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentledger_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='entry_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('project_bonus', 'Project Bonus'), ('bounty_payout', 'Bounty Payout'), ('milestone_bonus', 'Milestone Bonus'), ('materials_reimbursement', 'Materials Reimbursement'), ('payout', 'Payout'), ('adjustment', 'Adjustment'), ('chore_reward', 'Chore Reward'), ('coin_exchange', 'Coin Exchange'), ('homework_reward', 'Homework Reward')], max_length=25),
        ),
    ]
