# Generated by Django 5.1.15 on 2026-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentledger_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='entry_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('project_bonus', 'Project Bonus'), ('bounty_payout', 'Bounty Payout'), ('milestone_bonus', 'Milestone Bonus'), ('materials_reimbursement', 'Materials Reimbursement'), ('payout', 'Payout'), ('adjustment', 'Adjustment'), ('chore_reward', 'Chore Reward'), ('coin_exchange', 'Coin Exchange')], max_length=25),
        ),
    ]
