# Generated by Django 5.2.13 on 2026-04-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinledger",
            name="reason",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("project_bonus", "Project Bonus"),
                    ("bounty_bonus", "Bounty Bonus"),
                    ("milestone_bonus", "Milestone Bonus"),
                    ("badge_bonus", "Badge Bonus"),
                    ("redemption", "Redemption"),
                    ("refund", "Refund"),
                    ("adjustment", "Adjustment"),
                    ("chore_reward", "Chore Reward"),
                    ("exchange", "Exchange"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dollar_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("coin_amount", models.PositiveIntegerField()),
                (
                    "exchange_rate",
                    models.PositiveIntegerField(
                        help_text="COINS_PER_DOLLAR at time of request — authoritative for fulfillment."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("parent_notes", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
