# Generated by Django 5.2.13 on 2026-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinledger",
            name="reason",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("project_bonus", "Project Bonus"),
                    ("bounty_bonus", "Bounty Bonus"),
                    ("milestone_bonus", "Milestone Bonus"),
                    ("badge_bonus", "Badge Bonus"),
                    ("redemption", "Redemption"),
                    ("refund", "Refund"),
                    ("adjustment", "Adjustment"),
                    ("chore_reward", "Chore Reward"),
                ],
                max_length=20,
            ),
        ),
    ]
