# Generated by Django 5.2.4 on 2026-04-14
#
# Factored ``decided_by`` onto ``config.base_models.ApprovalWorkflowModel``
# and removed per-subclass ``related_name`` (now ``"+"`` — no reverse accessor).
# Schema-neutral: only the Python-level ``related_name`` changes.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_coinledger_reason_exchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
