# Generated by Django 5.2.4 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardredemption_use_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinledger',
            name='reason',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('project_bonus', 'Project Bonus'), ('bounty_bonus', 'Bounty Bonus'), ('milestone_bonus', 'Milestone Bonus'), ('badge_bonus', 'Badge Bonus'), ('redemption', 'Redemption'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('chore_reward', 'Chore Reward'), ('exchange', 'Exchange'), ('homework_reward', 'Homework Reward')], max_length=20),
        ),
    ]
