# Generated by Django 5.1.15 on 2026-04-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_coinledger_reason'),
        ('rpg', '0007_itemdefinition_sprite_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='fulfillment_kind',
            field=models.CharField(choices=[('real_world', 'Real-world (parent fulfills)'), ('digital_item', 'Digital item (inventory credit)'), ('both', 'Both')], default='real_world', max_length=16),
        ),
        migrations.AddField(
            model_name='reward',
            name='item_definition',
            field=models.ForeignKey(blank=True, help_text="Optional link to an RPG ItemDefinition. When set AND fulfillment_kind is digital_item or both, redemption approval credits one of this item to the user's UserInventory.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_rewards', to='rpg.itemdefinition'),
        ),
    ]
