# Generated by Django 5.1.15 on 2026-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_add_item_definition_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinledger',
            name='reason',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('project_bonus', 'Project Bonus'), ('bounty_bonus', 'Bounty Bonus'), ('milestone_bonus', 'Milestone Bonus'), ('badge_bonus', 'Badge Bonus'), ('redemption', 'Redemption'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('chore_reward', 'Chore Reward'), ('exchange', 'Exchange')], max_length=20),
        ),
    ]
