# Generated by Django 5.1.15 on 2026-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0009_add_reward_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinledger",
            name="reason",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("project_bonus", "Project Bonus"),
                    ("bounty_bonus", "Bounty Bonus"),
                    ("milestone_bonus", "Milestone Bonus"),
                    ("badge_bonus", "Badge Bonus"),
                    ("redemption", "Redemption"),
                    ("refund", "Refund"),
                    ("adjustment", "Adjustment"),
                    ("chore_reward", "Chore Reward"),
                    ("exchange", "Exchange"),
                    ("daily_challenge", "Daily Challenge"),
                ],
                max_length=20,
            ),
        ),
    ]
