# Generated by Django 5.2.4 on 2026-04-14 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0003_alter_subject_id'),
        ('rpg', '0003_itemdefinition_droptable_droplog_userinventory'),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⚔️', max_length=50)),
                ('quest_type', models.CharField(choices=[('boss', 'Boss Fight'), ('collection', 'Collection Quest')], max_length=20)),
                ('target_value', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('trigger_filter', models.JSONField(blank=True, default=dict)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quests', to=settings.AUTH_USER_MODEL)),
                ('required_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_quests', to='achievements.badge')),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('rage_shield', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='quests.questdefinition')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='QuestRewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_rewards', to='rpg.itemdefinition')),
                ('quest_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_items', to='quests.questdefinition')),
            ],
            options={
                'ordering': ['quest_definition', 'item'],
            },
        ),
        migrations.CreateModel(
            name='QuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.PositiveIntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contribution'],
                'unique_together': {('quest', 'user')},
            },
        ),
    ]
