# Generated by Django 5.2.13 on 2026-04-12 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("google_id", models.CharField(max_length=255, unique=True)),
                ("google_email", models.EmailField(max_length=254)),
                (
                    "encrypted_credentials",
                    models.BinaryField(
                        help_text="Fernet-encrypted JSON of access_token, refresh_token, expiry, scopes."
                    ),
                ),
                ("calendar_sync_enabled", models.BooleanField(default=False)),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Google Calendar ID to sync events to.",
                        max_length=255,
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent who linked this account (for child accounts).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_google_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google account",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.CharField(
                        help_text='Discriminator, e.g. "project_due", "chore", "time_entry".',
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("google_event_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar event mapping",
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
