# Generated by Django 5.2.5 on 2026-05-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPTokenResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(db_index=True, max_length=512)),
                ('access_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_resource', to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
            options={
                'verbose_name': 'MCP token resource binding',
                'verbose_name_plural': 'MCP token resource bindings',
            },
        ),
    ]
