# Generated by Django 5.2.4 on 2026-04-23 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0011_alter_badge_criteria_type'),
        ('chronicle', '0004_alter_chronicleentry_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='creations/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='creations/audio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('occurred_on', models.DateField(help_text='Local-day bucket used by the anti-farm gate and chapter_year.')),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='logged', max_length=16)),
                ('xp_awarded', models.PositiveIntegerField(default=0, help_text='Baseline self-credit XP pool distributed on log (0 if over daily cap).')),
                ('bonus_xp_awarded', models.PositiveIntegerField(default=0, help_text='Additional XP pool granted by parent on approve.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('chronicle_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chronicle.chronicleentry')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_skill', models.ForeignKey(help_text='Required. Must be in a creative category (see apps.creations.constants).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='achievements.skill')),
                ('secondary_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='achievements.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreationBonusSkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_weight', models.PositiveIntegerField(default=1)),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_skill_tags', to='creations.creation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achievements.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CreationDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_daily_counters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['user', 'occurred_on'], name='creations_c_user_id_0a1cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['user', 'status'], name='creations_c_user_id_599f85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creationbonusskilltag',
            unique_together={('creation', 'skill')},
        ),
        migrations.AddIndex(
            model_name='creationdailycounter',
            index=models.Index(fields=['user', 'occurred_on'], name='creations_c_user_id_1421c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creationdailycounter',
            unique_together={('user', 'occurred_on')},
        ),
    ]
