# Generated by Django 5.2.12 on 2026-04-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphoto",
            name="is_timelapse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectphoto",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube/external video link or time-lapse URL",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectphoto",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio/"),
        ),
    ]
