# Generated by Django 5.2.4 on 2026-04-14 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('food_preference', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'pet species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(default='#8B7355', max_length=7)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mounts', to='pets.potiontype')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mounts', to='pets.petspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'species__name'],
                'unique_together': {('user', 'species', 'potion')},
            },
        ),
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('growth_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('evolved_to_mount', models.BooleanField(default=False)),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pets', to='pets.potiontype')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pets', to='pets.petspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'species__name'],
                'unique_together': {('user', 'species', 'potion')},
            },
        ),
    ]
