# Generated by Django 5.2.4 on 2026-04-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspecies',
            name='available_potions',
            field=models.ManyToManyField(blank=True, help_text='Potion variants that can hatch this species.', related_name='species', to='pets.potiontype'),
        ),
        migrations.AddField(
            model_name='petspecies',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='potiontype',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
