# Sync notification choices with the model. Adds the seven Forge (3D print
# request) kinds:
#   print_request_submitted  — a child filed a request (fans out to parents)
#   print_request_approved   — a parent approved it and the plate name was minted
#   print_request_rejected   — a parent declined it
#   print_started            — the MQTT listener saw the plate go on the printer
#   print_finished           — the print completed and the budget was debited
#   print_failed             — the print stopped; the message carries the decoded
#                              HMS / print_error reason, not a raw code
#   print_budget_low         — the child is near their monthly filament allowance

# Generated by Django 5.1.15 on 2026-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_streak_at_risk_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("timecard_ready", "Timecard Ready"),
                    ("timecard_approved", "Timecard Approved"),
                    ("badge_earned", "Badge Earned"),
                    ("project_approved", "Project Approved"),
                    ("project_changes", "Changes Requested"),
                    ("payout_recorded", "Payout Recorded"),
                    ("skill_unlocked", "Skill Unlocked"),
                    ("milestone_completed", "Milestone Completed"),
                    ("redemption_requested", "Redemption Requested"),
                    ("chore_submitted", "Chore Submitted"),
                    ("chore_approved", "Chore Approved"),
                    ("chore_rejected", "Chore Rejected"),
                    ("exchange_requested", "Exchange Requested"),
                    ("exchange_approved", "Exchange Approved"),
                    ("exchange_denied", "Exchange Denied"),
                    ("project_due_soon", "Project Due Soon"),
                    ("chore_reminder", "Chore Reminder"),
                    ("approval_reminder", "Approval Reminder"),
                    ("homework_created", "Homework Created"),
                    ("homework_submitted", "Homework Submitted"),
                    ("homework_approved", "Homework Approved"),
                    ("homework_rejected", "Homework Rejected"),
                    ("homework_due_soon", "Homework Due Soon"),
                    ("streak_milestone", "Streak Milestone"),
                    ("streak_at_risk", "Streak At Risk"),
                    ("perfect_day", "Perfect Day"),
                    ("daily_check_in", "Daily Check-In"),
                    ("savings_goal_completed", "Savings Goal Completed"),
                    ("birthday", "Birthday"),
                    ("chronicle_first_ever", "Chronicle — first ever"),
                    ("comeback_suggested", "Comeback Quest Suggested"),
                    ("creation_submitted", "Creation Submitted"),
                    ("creation_approved", "Creation Approved"),
                    ("creation_rejected", "Creation Rejected"),
                    ("chore_proposed", "Duty Proposed"),
                    ("habit_proposed", "Ritual Proposed"),
                    ("chore_proposal_approved", "Duty Proposal Approved"),
                    ("habit_proposal_approved", "Ritual Proposal Approved"),
                    ("chore_proposal_rejected", "Duty Proposal Rejected"),
                    ("habit_proposal_rejected", "Ritual Proposal Rejected"),
                    ("quest_completed", "Quest Completed"),
                    ("drop_received", "Drop Received"),
                    ("pet_evolved", "Pet Evolved"),
                    ("mount_bred", "Mount Bred"),
                    ("low_reward_stock", "Reward Stock Low"),
                    ("reward_restocked", "Reward Back In Stock"),
                    ("expedition_returned", "Expedition Returned"),
                    ("print_request_submitted", "Print Request Submitted"),
                    ("print_request_approved", "Print Request Approved"),
                    ("print_request_rejected", "Print Request Rejected"),
                    ("print_started", "Print Started"),
                    ("print_finished", "Print Finished"),
                    ("print_failed", "Print Failed"),
                    ("print_budget_low", "Print Budget Low"),
                ],
                max_length=25,
            ),
        ),
    ]
